server {
    listen 80;
    server_name tu_dominio_o_ip;

    location / {
        root /var/www/tu_app/dist;
        index index.html;
        try_files $uri $uri/ /index.html; 
    }

    location /api/ {
        proxy_pass http://unix:/run/gunicorn.sock;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /media/ {
        alias /var/www/tu_app/media/;
    }
}